version: '3.4'

services:
  bookshopapp:
    image: bookshopapp
    build:
      context: .
      dockerfile: BookshopApp.Presentation/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
